version: '3.8'

services:
  web:
    image: ercihankorkmaz/qr-code-api:latest
    ports:
      - "80:80"
    volumes:
      - ./qr_codes:/app/qr_codes
    environment:
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=secret
      - SERVER_BASE_URL=http://localhost:80
      - SERVER_DOWNLOAD_FOLDER=downloads
